version: '3.8'
services:
  shortener:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/shortener
    entrypoint: ["python", "shortener.py"]
  client:
    restart: always
    build: .
    ports:
      - 5050:5050
    volumes:
      - .:/shortener
    depends_on:
          - shortener
    entrypoint: ["python", "client.py"]
